[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Generate Prisma client and run migrations before starting the app
[[deploy.initCommands]]
cmd = "npx prisma generate"

[[deploy.initCommands]]
cmd = "npx prisma migrate deploy"

[env]
NODE_ENV = "production"
