[build]
builder = "NIXPACKS"
buildCommand = "pnpm run deploy:railway"

[deploy]
startCommand = "node dist/src/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
