apiVersion: v1
kind: Secret
metadata:
  name: oprix-secrets
type: Opaque
stringData:
  # Database
  database-url: "postgresql://user:password@postgres-service:5432/oprix_ctf"
  
  # JWT
  jwt-secret: "CHANGE_THIS_IN_PRODUCTION"
  
  # Clerk
  clerk-frontend-api: "https://your-app.clerk.accounts.dev"
  clerk-secret-key: "sk_live_xxxxxxxxxxxxx"
  
  # Redis
  redis-password: ""
  
  # SuperAdmin
  superadmin-password: "CHANGE_THIS_IN_PRODUCTION"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oprix-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CORS_ORIGIN: "https://yourdomain.com"
